### ISSUE TITLE
第二次加载时   js 初始化 方法没有调用

### ISSUE THREAD

**Issue by zhanghongbin5177** [writethesky/application.js#9]
271行   js_name    =   public/js/member.js

w[js_name]()     初始化方法调用时    js_name  不能带有路径  只能为 js文件的名字 如  member.js

**Comment by writethesky** [comment]
已经修复，使用方法参考

[https://github.com/writethesky/application.js#命名空间](url)

[https://github.com/writethesky/application.js#构造函数](url)
